name: Build GorillaBlackOpsHUD

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet (even though we only have file refs)
        run: dotnet restore GorillaBlackOpsHUD.csproj

      - name: Build DLL
        run: msbuild GorillaBlackOpsHUD.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Rebuild

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GorillaBlackOpsHUD
          path: bin/Release/GorillaBlackOpsHUD.dll
