name: Build GorillaBlackOpsHUD

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2

      - name: Restore (needed for net472 SDK targets)
        run: dotnet restore GorillaBlackOpsHUD.csproj

      - name: Build DLL
        run: msbuild GorillaBlackOpsHUD.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Rebuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GorillaBlackOpsHUD
          path: bin/Release/GorillaBlackOpsHUD.dll
